### PR TITLE
Feature/add locale to has

### PR DESCRIPTION
**Pull request by jhuliano**
Solves issue #4 and adds locale usage to other functions

### CODE REVIEW

**Comment by rmariuzzo** [comment]
Everything looks good @jhuliano! Can you add some tests cases to `test/spec/lang_has_spec.js`?

**Comment by jhuliano** [comment]
Sure! I will check on that tomorrow (today?) :+1:

**Comment by gpopoteur** [comment]
@jhuliano @rmariuzzo I'm working on issues #5 and #6, will base my branch on this one as I need the modifications in the `has()` and `_getMessage()` methods.

**Comment by jhuliano** [comment]
@rmariuzzo I last commit should cover the usage of locale in "has". LMK if I missed anything.

**Comment by rmariuzzo** [comment]
@jhuliano if you get some time, try to merge the upstream develop into your branch or rebase. We have made some changes that don't let me merge your change automatically. If you can't I will have a look in the next 24 hours.

**Comment by jhuliano** [comment]
@rmariuzzo NP, I will check into it tonight.

**Comment by rmariuzzo** [comment]
@jhuliano thanks!

**Comment by gpopoteur** [comment]
@rmariuzzo could this PR be merged? I'm basing my PRs on this one.

**Comment by rmariuzzo** [comment]
I'm checking this now @gpopoteur

**Comment by rmariuzzo** [comment]
@gpopoteur done!
@jhuliano thanks a lot for your support on this!

**Comment by gpopoteur** [comment]
@rmariuzzo thanks :grin: I'll be submitting my PRs during the week :)

**Comment by rmariuzzo** [comment]
Thank you! :bow:

**Pull request merged**
