### PR TITLE
Implement transChoice method

### PR DESCRIPTION
**Pull request by esantelises**
Solve issue #8 implement `transChoice` method.

### CODE REVIEW

**Comment by rmariuzzo** [comment]
All good @esantelises! Although is not an alias, I think it is what we want right now. Thanks a lot!

**Comment by esantelises** [comment]
hey @rmariuzzo, looks like i have mis concept on how to create function alias, for the knowledge can you point me right direction? :)

**Comment by rmariuzzo** [comment]
As @kamilogorek mentioned it in https://github.com/rmariuzzo/Lang.js/issues/7#issuecomment-133770453 he did well explaining that:

> It should use one reference to the same function, not be created as a separate one. Otherwise it won't be an alias and it will duplicate call stack and eventual error stack trace.
>
> ```js
> Lang.prototype.get = Lang.prototype.trans = function (key, replacement) { ... } 
> ```

But, I think it is good enough as you did it. I didn't use the proper term when I said alias, but I meant what you did. It allow to add the JsDoc to the `trans()` method. Although, I don't know if creating an alias will make doc-generator to identify it. That last, will be another story.

**Comment by esantelises** [comment]
understood :+1:  thanks for clarification

**Pull request merged**
