### PR TITLE
Added support dot in keys for any depth. Fix for #54 

### PR DESCRIPTION
**Pull request by vteremasov**
Added minimum changes

### CODE REVIEW

**Comment by rmariuzzo** [comment]
Hey @vteremasov! I have received 3 PRs along with yours. I merged into develop branch the one that was more complete. Your solution is good, sorry because I can only choose one. Right now, I have pushed into develop a tricky test which need to pass so we can deliver this feature. If you want to grab it, please let me know. :)

I'm closing this one, as your proposed solution has been merged.

**Comment by vteremasov** [comment]
@rmariuzzo Thank you for your feedback

**Comment by rgehan** [comment]
@rmariuzzo Actually his implementation allows for dotted keys in the middle of the path also, so that such a tree can be used:
```
{
    "dotted.category": {
        "dot.in.key": "Dot in Key"
    }
}
```

Perhaps he could tweak my code so that it also works that way. We'd have the best of both worlds

**Comment by rmariuzzo** [comment]
@rgehan true... I apologize @vteremasov for hurrying over you proposes changes. Would it be easy for you to apply your change over the current state of `develop` branch.

If not, I will try to pull his changes instead @rgehan and test.

**Comment by rgehan** [comment]
It can be quite easily integrated into my code, you only need to tweak the inside of the loop in `findMessageInTree`. I'll add a commit to my PR if necessary.

**Comment by rmariuzzo** [comment]
I'll be more than grateful if you can take it @rgehan

**Comment by rgehan** [comment]
I'll look at it tonight or tomorrow, most probably on my previous PR

**Comment by rmariuzzo** [comment]
Awesome @rgehan! Thank you mate for your willingness!

**Pull request merged**
