### PR TITLE
Added plural form for all the locales available in Laravel

### PR DESCRIPTION
**Pull request by a-komarev**
My piece of work for this issue: #6 

Isolated tests and new group of messages added for this use case.

*// I've wrote Zend Framework copyrights because it's converted part of PHP code from Laravel translator and it has Zend copyrights too. Not sure if there should be the copyrights in this case.*

### CODE REVIEW

**Comment by rmariuzzo** [comment]
Thanks @a-komarev! Would you like to be a collaborator for this lib and Laravel-JS-Translator projects? I have seen your willingness.

**Comment by a-komarev** [comment]
@rmariuzzo Will glad to join. But I don't have a lot of free time at this moment.

**Comment by rmariuzzo** [comment]
Even if it is not too much... but if you can help us take better decisions and help us on reviewing PR at your own time... what do you think?

**Comment by a-komarev** [comment]
@rmariuzzo sure, if I will have a time - I will keep an eye on the changes.

**Comment by rmariuzzo** [comment]
Thank you!

**Comment by rmariuzzo** [comment]
Fixed #27

**Pull request merged**
