### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nivla**

### CODE REVIEW

**Comment by rmariuzzo** [comment]
Good catch @nivla !

**Comment by rmariuzzo** [comment]
@nivla can you recreate this PR but merging into develop branch instead of master?

**Comment by nivla** [comment]
Of course :D

**Comment by rmariuzzo** [comment]
Thanks @nivla! I have also changed the default branch to `develop` so the process of creating PR and commits will be more straightforward.

**Pull request merged**
